### ISSUE TITLE
HTML Table Names

### ISSUE THREAD

**Issue by athrun22** [EnergizingWatermelon/DungeonWizard#16]
In order to have a check for a specific table, to make sure a map exists on the page, it would really help if the tables were named, i.e.  the map generator's table of tiles for the map is named 'maps' and the same for both adventures and encounters.

**Comment by shanemcdermott** [comment]
Correct me if I'm misunderstanding you, but currently all maps are within an HTML div class named "map".

**Comment by athrun22** [comment]
They are in a div class called "col-md-12", but the table is in a class called map.  I need one of those two to have an id that says "map" if possible, or I can try and use the "col-md-12" class if you don't think that will change.

**Comment by shanemcdermott** [comment]
Alright, the "col-md-12" class now has an id of "map"

**Comment by athrun22** [comment]
Thanks Shane, did you push that to Encounters or Development?

**Comment by shanemcdermott** [comment]
It's currently in encounters
